# -*- coding: utf-8 -*-
"""test_model.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAHr7Y-DFqfBiYx1zltT7cbZ5jnpjENl
"""

import unittest
import numpy as np
from linearregression import reg, height, weight

class TestLinearRegression(unittest.TestCase):
    def test_prediction(self):
        # Test prediction for height 12.0
        X_height = [[12.0]]
        predicted_weight = reg.predict(X_height)
        
        # Calculate the expected prediction using the linear regression formula (intercept and coefficient)
        intercept = reg.intercept_
        coef = reg.coef_[0]
        expected_weight = intercept + coef * X_height[0][0]  # Linear regression formula: y = mx + b

        # Assert that the predicted value is close to the expected value
        self.assertAlmostEqual(predicted_weight[0], expected_weight, delta=0.1)

if __name__ == '__main__':
    unittest.main()
