# -*- coding: utf-8 -*-
"""test_model.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAHr7Y-DFqfBiYx1zltT7cbZ5jnpjENl
"""

import unittest
import numpy as np
from linearregression import reg

class TestLinearRegression(unittest.TestCase):
    def test_prediction(self):
        # Test prediction for height 12.0
        X_height = [[12.0]]
        predicted_weight = reg.predict(X_height)
        
        # Since this is a simple model, we know the expected value based on our input data
        expected_weight = 144.0  # The square of 12, similar to the pattern in weight data
        
        # Assert that the predicted value is close to the expected value
        self.assertAlmostEqual(predicted_weight[0], expected_weight, delta=0.1)

if __name__ == '__main__':
    unittest.main()
